[build.environment]
  HUGO_VERSION = "0.147.3"
  GO_VERSION = "1.22.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "22.16.0"

[build]
  publish = "public"
  command = "npm install && hugo --minify"

[context.production.environment]
  HUGO_ENV = "production"

[[headers]]
  for = "/index.json"
  [headers.values]
    Cache-Control = "no-cache"
