[build.environment]
  HUGO_VERSION = "0.147.3"
  GO_VERSION = "1.22.2"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "22.16.0"

[build]
  publish = "public"
  command = "npm install && hugo --minify"

[context.production.environment]
  HUGO_ENV = "production"

# Prevent caching index.json (used by Lunr.js)
[[headers]]
  for = "/index.json"
  [headers.values]
    Cache-Control = "no-cache"

# Global security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      object-src 'none';
      base-uri 'self';
    '''
